### ISSUE TITLE
TypeError: this._reject is not a function

### ISSUE THREAD

**Issue by mrvic** [MDSLab/node-reverse-wstunnel#12]
Hello,

**Using** crome browser  
**When** going to **http://localhost:3333** 
**I was expecting to** get website hosted at **http://10.216.5.47:8000**
**Instead** server crashed:

**CLIENT**
[winMachine]$ **`node wstt.js -t 3333 ws://10.216.5.47:8888`**
Connection detected 

**SERVER**
[root@partedmagic bin]$**` ./wstt.js -s 8888 -t 127.0.0.1:8000`**
Tue Dec 13 2016 14:08:27 GMT+0100 (CET) Server is listening on port 8888
/home/user/node_modules/node-reverse-wstunnel/lib/wst_server.js:78
            return this._reject(request, "Tunnel connect error to " + remoteAddr + ": " + err);
                        ^

TypeError: this._reject is not a function
    at Socket.<anonymous> (/home/user/node_modules/node-reverse-wstunnel/lib/wst_server.js:78:25)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at emitErrorNT (net.js:1276:8)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
[root@partedmagic bin]$ ./wstt.js -s 8888 -t 127.0.0.1:8000
Tue Dec 13 2016 14:09:20 GMT+0100 (CET) Server is listening on port 8888
/home/user/node_modules/node-reverse-wstunnel/lib/wst_server.js:78
            return this._reject(request, "Tunnel connect error to " + remoteAddr + ": " + err);

**Comment by npeditto** [comment]
Bug fixed in "refactoring" branch...soon it will be merged  with "master".
