### ISSUE TITLE
Unable to bind server to a specific IP

### ISSUE THREAD

**Issue by uidzero** [MDSLab/node-reverse-wstunnel#7]
```
$ ./wstt.js -s 2222
Thu Aug 06 2015 14:41:27 GMT+0000 (UTC) Server is listening on port 2222

# lsof -ni|grep node
node      5857   wstunnel   10u  IPv4 25660001      0t0  TCP *:2222 (LISTEN)
```
[...]

```
$ ./wstt.js -s 127.0.0.1:2222 
Thu Aug 06 2015 14:40:43 GMT+0000 (UTC) Server is listening on port 127.0.0.1:2222

# lsof -ni|grep node
#
```
It also creates the -s target as a socket in ```.```:
```
srwxrwxr-x 1 wstunnel wstunnel     0 Aug  6 14:40 127.0.0.1:2222
```

It doesn't seem to create the socket when just the port is specified.

If it's listening to external traffic then most of the purpose of putting it behind an HTTPS proxy is defeated.

**Comment by uidzero** [comment]
I see this line in ```lib/wst_server.js:58```:

```
          _ref = [_this.dstHost, _this.dstPort], host = _ref[0], port = _ref[1];
```

If this is the correct line then it is failing silently somehow. I don't know node.js well enough to track down the issue.

**Comment by alotronto** [comment]
Sorry uidzero for the delay, but I am the only one developer and maintainer of the node-reverse-wstunnel project.

Could you specify if you want to realize a reverse websocket tunnel or only a websocket tunnel?
