### ISSUE TITLE
Can this work as a load balancer?

### ISSUE THREAD

**Issue by jimmywarting** [MDSLab/node-reverse-wstunnel#9]
I have built something similar before with socket.io but this seems way better then what i built.

I have currently 3 servers (slaves) that are connected to one master that handels all request and distributes them over to all slaves throught socket.io

Can something similar be done with this package?

**Comment by alotronto** [comment]
no it can not work as loader balancer. When you use this library, you create a connection point to point between client and server, one public port on the server is mapped to a client. The library born to map one connection on the server with one service on the client.
